// @MX:NOTE: [AUTO] Test fixtures for export functionality E2E tests
// @MX:SPEC: SPEC-REGULA-EXPORT-HUB-001 (T-050)

export const sampleArtifactContent = `# Regulatory Analysis Summary

## Overview
This document provides a comprehensive analysis of the regulatory requirements for medical device classification under FDA 21 CFR.

## Key Findings

### Classification Criteria
Based on **21 CFR 862.2100**, medical device classification depends on:
1. Intended use
2. Risk level
3. Regulatory pathway

### Compliance Requirements
- **Premarket Notification (510(k))**: Required for Class II devices
- **Premarket Approval (PMA)**: Required for Class III devices
- **General Controls**: Apply to all device classes

## Risk Assessment
The device in question falls under **Class II** category due to moderate risk profile.

## References
[1] FDA 21 CFR 862.2100 - Class II Special Controls
[2] FDA 21 CFR 807 - Subpart B - Premarket Notification
[3] EU MDR 2017/745 - Medical Device Regulation`;

export const sampleCitations = [
  {
    id: 1,
    source: 'FDA 21 CFR 862.2100',
    title: 'Class II Special Controls',
    corpus: 'FDA 21 CFR',
    page_reference: 'Section 862.2100',
    url: 'https://www.ecfr.gov/current/title-21/section-862.2100',
    relevance_score: 0.95
  },
  {
    id: 2,
    source: 'FDA 21 CFR 807',
    title: 'Premarket Notification',
    corpus: 'FDA 21 CFR',
    page_reference: 'Subpart B',
    url: 'https://www.ecfr.gov/current/title-21/chapter-I/subchapter-H/part-807',
    relevance_score: 0.92
  },
  {
    id: 3,
    source: 'EU MDR 2017/745',
    title: 'Medical Device Regulation',
    corpus: 'EU MDR',
    page_reference: 'Article 1-5',
    url: 'https://health.ec.europa.eu/medical-devices-sector/new-regulations',
    relevance_score: 0.88
  }
];

export const expectedMarkdownOutput = `# Regulatory Analysis Summary

## Overview
This document provides a comprehensive analysis of the regulatory requirements for medical device classification under FDA 21 CFR.

## Key Findings

### Classification Criteria
Based on **21 CFR 862.2100**, medical device classification depends on:
1. Intended use
2. Risk level
3. Regulatory pathway

### Compliance Requirements
- **Premarket Notification (510(k))**: Required for Class II devices
- **Premarket Approval (PMA)**: Required for Class III devices
- **General Controls**: Apply to all device classes

## Risk Assessment
The device in question falls under **Class II** category due to moderate risk profile.

## References

1. FDA 21 CFR 862.2100 - Class II Special Controls
   Source: FDA 21 CFR, Section 862.2100
   URL: https://www.ecfr.gov/current/title-21/section-862.2100

2. FDA 21 CFR 807 - Premarket Notification
   Source: FDA 21 CFR, Subpart B
   URL: https://www.ecfr.gov/current/title-21/chapter-I/subchapter-H/part-807

3. EU MDR 2017/745 - Medical Device Regulation
   Source: EU MDR, Article 1-5
   URL: https://health.ec.europa.eu/medical-devices-sector/new-regulations`;

export const expectedDOCXMetadata = {
  title: 'Regula Regulatory Analysis',
  author: 'RA Lead',
  subject: 'Medical Device Classification Analysis',
  creator: 'Regula Export System',
  description: 'Comprehensive regulatory analysis for medical device compliance'
};

export const expectedPDFOptions = {
  format: 'A4',
  margin: '1 inch',
  header: true,
  footer: true,
  pageNumbers: true,
  branding: true
};

export const expectedEmailFormat = {
  subject: 'Regula Regulatory Analysis - [Date]',
  body: `Regulatory Analysis Summary

This analysis was generated by Regula, the medical device regulatory affairs AI assistant.

[Content would be included here]

---
Regula - Medical Device Regulatory Intelligence
© 2026 Regula. All rights reserved.`,
  recipients: [] // User adds recipients
};

// Mock audit log entries for testing
export const mockAuditLogs = [
  {
    id: 1,
    action: 'artifact_exported_markdown',
    action_type: 'artifact_exported',
    user_id: 'test-user-123',
    resource_type: 'answer',
    resource_id: 'msg-456',
    details: {
      format: 'markdown',
      filename: 'regula-export-20260620.md',
      size: 2048
    },
    created_at: '2026-06-20T10:30:00Z',
    ip_address: '127.0.0.1'
  },
  {
    id: 2,
    action: 'artifact_exported_docx',
    action_type: 'artifact_exported',
    user_id: 'test-user-123',
    resource_type: 'answer',
    resource_id: 'msg-456',
    details: {
      format: 'docx',
      filename: 'regula-export-20260620.docx',
      size: 8192
    },
    created_at: '2026-06-20T10:31:00Z',
    ip_address: '127.0.0.1'
  },
  {
    id: 3,
    action: 'artifact_exported_pdf',
    action_type: 'artifact_exported',
    user_id: 'test-user-123',
    resource_type: 'answer',
    resource_id: 'msg-456',
    details: {
      format: 'pdf',
      filename: 'regula-export-20260620.pdf',
      size: 15360
    },
    created_at: '2026-06-20T10:32:00Z',
    ip_address: '127.0.0.1'
  },
  {
    id: 4,
    action: 'artifact_exported_email',
    action_type: 'artifact_exported',
    user_id: 'test-user-123',
    resource_type: 'answer',
    resource_id: 'msg-456',
    details: {
      format: 'email',
      subject: 'Regula Regulatory Analysis - 2026-06-20'
    },
    created_at: '2026-06-20T10:33:00Z',
    ip_address: '127.0.0.1'
  }
];

// Helper function to create mock export response
export function createMockExportResponse(format: string) {
  return {
    success: true,
    content: sampleArtifactContent,
    filename: `regula-export-${format.toLowerCase()}-20260620.${format.toLowerCase()}`,
    format,
    timestamp: new Date().toISOString(),
    citations: sampleCitations
  };
}

// Helper function to simulate export failure
export function createMockExportFailure(format: string, errorMessage: string) {
  return {
    success: false,
    error: {
      message: errorMessage,
      code: 'EXPORT_ERROR',
      format
    }
  };
}