/**
 * DOCXExporter class
 * SPEC-REGULA-EXPORT-HUB-001 Phase 4 (T-016, T-017, T-018, T-019, T-020, T-021)
 * REQ-EXP-001, REQ-EXP-002, REQ-EXP-003: DOCX export with citations, headers, and metadata
 * @MX:SPEC SPEC-REGULA-EXPORT-HUB-001
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  UnderlineType,
 convertInchesToTwip,
  PackageProperties
} from 'docx';
import { BaseExporter } from '../base-exporter';
import { ExportFormat, ExportOptions, ExportResult } from '../types';
import { ExportErrorCode } from '../types';

/**
 * Data structure for DOCX export with metadata
 */
interface DOCXData {
  content: string;
  title?: string;
  author?: string;
  citations?: Array<{ text: string; url?: string }>;
  convertHeaders?: boolean;
  addBranding?: boolean;
}

/**
 * DOCXExporter - Export data to DOCX format
 * Supports citation hyperlinks, section headers with Word styles, and document metadata
 * @MX:NOTE Implements REQ-EXP-001 (DOCX generation), REQ-EXP-002 (citation hyperlinks), REQ-EXP-003 (header styles)
 */
export class DOCXExporter extends BaseExporter {
  /**
   * Export data to DOCX format
   */
  async export(data: unknown, options: ExportOptions): Promise<ExportResult> {
    try {
      this.validateOptions(options);

      if (!(await this.validate(data, options))) {
        return this.createErrorResult(
          options.format,
          ExportErrorCode.VALIDATION_ERROR,
          'Invalid data for DOCX export'
        );
      }

      const docxData = data as DOCXData;

      // Create DOCX document
      const doc = this.createDocument(docxData, options);

      // Generate DOCX buffer
      const buffer = await Packer.toBuffer(doc);

      // Convert buffer to base64 string for download
      const content = buffer.toString('base64');

      // Ensure .docx extension
      const baseFilename = options.customFilename || `export-${this.getTimestamp()}`;
      const filename = baseFilename.endsWith('.docx') ? baseFilename : `${baseFilename}.docx`;

      const blob = new Blob([buffer], {
        type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
      });

      return {
        success: true,
        format: options.format,
        content,
        filename,
        size: blob.size,
        timestamp: new Date(),
      };
    } catch (error) {
      return this.createErrorResult(
        options.format,
        ExportErrorCode.GENERATION_FAILED,
        error instanceof Error ? error.message : 'Unknown error'
      );
    }
  }

  /**
   * Validate that the export can be performed
   */
  async validate(data: unknown, options: ExportOptions): Promise<boolean> {
    if (options.format !== this.getFormat()) {
      return false;
    }

    const docxData = data as DOCXData;
    return !!(docxData && docxData.content);
  }

  /**
   * Get the format this exporter handles
   */
  getFormat(): ExportFormat {
    return ExportFormat.DOCX;
  }

  /**
   * Create DOCX document from data
   */
  private createDocument(data: DOCXData, options: ExportOptions): Document {
    const paragraphs: Paragraph[] = [];

    // Add title if present and metadata is included
    if (options.includeMetadata && data.title) {
      paragraphs.push(
        new Paragraph({
          text: data.title,
          heading: HeadingLevel.HEADING_1,
          alignment: AlignmentType.CENTER,
          spacing: {
            after: convertInchesToTwip(0.2),
          },
        })
      );
    }

    // Add Regula branding if enabled
    if (data.addBranding) {
      paragraphs.push(
        new Paragraph({
          children: [
            new TextRun({
              text: 'Generated by Regula - Regulatory Affairs AI Assistant',
              italics: true,
              size: 18, // 9pt
              color: '666666',
            }),
          ],
          alignment: AlignmentType.CENTER,
          spacing: {
            after: convertInchesToTwip(0.3),
          },
        })
      );
    }

    // Parse content and convert to paragraphs
    const contentParagraphs = this.parseContent(data.content, data.convertHeaders || false);
    paragraphs.push(...contentParagraphs);

    // Add citations if metadata is included
    if (options.includeMetadata && data.citations && data.citations.length > 0) {
      paragraphs.push(
        new Paragraph({
          text: 'References',
          heading: HeadingLevel.HEADING_2,
          spacing: {
            before: convertInchesToTwip(0.2),
            after: convertInchesToTwip(0.1),
          },
        })
      );

      data.citations.forEach((citation) => {
        if (citation.url) {
          // Add citation as hyperlink
          paragraphs.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: citation.text,
                  underline: {
                    type: UnderlineType.SINGLE,
                  },
                  color: '0000FF',
                }),
              ],
              spacing: {
                after: convertInchesToTwip(0.1),
              },
            })
          );
        } else {
          // Add citation as plain text
          paragraphs.push(
            new Paragraph({
              text: citation.text,
              spacing: {
                after: convertInchesToTwip(0.1),
              },
            })
          );
        }
      });
    }

    // Create document with metadata
    const docProperties = {
      title: data.title || 'Regula Export',
      creator: data.author || 'Regula',
      description: 'Generated by Regula - Regulatory Affairs AI Assistant',
    };

    return new Document({
      sections: [
        {
          properties: {},
          children: paragraphs,
        },
      ],
      ...docProperties,
    });
  }

  /**
   * Parse content and convert to DOCX paragraphs
   * Supports markdown-style headers (# ## ###)
   */
  private parseContent(content: string, convertHeaders: boolean): Paragraph[] {
    const lines = content.split('\n');
    const paragraphs: Paragraph[] = [];

    for (const line of lines) {
      const trimmedLine = line.trim();

      // Skip empty lines
      if (!trimmedLine) {
        continue;
      }

      // Check for markdown-style headers if convertHeaders is enabled
      if (convertHeaders) {
        if (trimmedLine.startsWith('# ')) {
          paragraphs.push(
            new Paragraph({
              text: trimmedLine.substring(2),
              heading: HeadingLevel.HEADING_1,
              spacing: {
                before: convertInchesToTwip(0.1),
                after: convertInchesToTwip(0.1),
              },
            })
          );
          continue;
        } else if (trimmedLine.startsWith('## ')) {
          paragraphs.push(
            new Paragraph({
              text: trimmedLine.substring(3),
              heading: HeadingLevel.HEADING_2,
              spacing: {
                before: convertInchesToTwip(0.1),
                after: convertInchesToTwip(0.1),
              },
            })
          );
          continue;
        } else if (trimmedLine.startsWith('### ')) {
          paragraphs.push(
            new Paragraph({
              text: trimmedLine.substring(4),
              heading: HeadingLevel.HEADING_3,
              spacing: {
                before: convertInchesToTwip(0.1),
                after: convertInchesToTwip(0.1),
              },
            })
          );
          continue;
        }
      }

      // Regular paragraph
      paragraphs.push(
        new Paragraph({
          text: trimmedLine,
          spacing: {
            after: convertInchesToTwip(0.1),
          },
        })
      );
    }

    return paragraphs;
  }

  /**
   * Generate timestamp for filename
   * Format: YYYYMMDDHHmmss
   */
  private getTimestamp(): string {
    const now = new Date();
    const year = now.getFullYear();
    const month = String(now.getMonth() + 1).padStart(2, '0');
    const day = String(now.getDate()).padStart(2, '0');
    const hours = String(now.getHours()).padStart(2, '0');
    const minutes = String(now.getMinutes()).padStart(2, '0');
    const seconds = String(now.getSeconds()).padStart(2, '0');

    return `${year}${month}${day}${hours}${minutes}${seconds}`;
  }
}
