// @MX:SPEC SPEC-REGULA-PCCP-001 (REQ-PCCP-019)
// PCCP PDF export — real document generation via @react-pdf/renderer.
// Renders device header, optional DRAFT watermark, and one section per
// component with its content_jsonb rendered as structured key-value text.

import type { PccpComponentRecord, PccpComponentType, PccpVersion } from '../types';
import { flattenContent } from './content-flatten';

export interface PccpPdfExportOptions {
  includeDraftWatermark: boolean;
}

/** Human-readable labels for each PCCP component type. */
const COMPONENT_LABELS: Record<PccpComponentType, string> = {
  modification_description: 'Modification Description',
  sps: 'Software Pre-Specifications (SPS)',
  acp: 'Algorithm Change Protocol (ACP)',
  impact_assessment: 'Impact Assessment',
  performance_testing: 'Performance Testing',
};

/**
 * Generates a PDF buffer for the given PCCP version and its components.
 * Uses @react-pdf/renderer (already a project dependency) with lazy import
 * to avoid React initialization side-effects in unit tests.
 */
export async function exportPccpToPdf(
  version: PccpVersion,
  components: PccpComponentRecord[],
  options: PccpPdfExportOptions,
): Promise<Buffer> {
  const { Document, Page, Text, View, StyleSheet, pdf } = await import('@react-pdf/renderer');

  const styles = StyleSheet.create({
    page: {
      paddingTop: 36,
      paddingBottom: 50,
      paddingHorizontal: 48,
      fontSize: 11,
      fontFamily: 'Helvetica',
      lineHeight: 1.5,
    },
    title: { fontSize: 20, fontFamily: 'Helvetica-Bold', marginBottom: 4 },
    subtitle: { fontSize: 11, color: 'rgb(74, 85, 104)', marginBottom: 16 },
    sectionHeading: {
      fontSize: 14,
      fontFamily: 'Helvetica-Bold',
      marginTop: 16,
      marginBottom: 6,
      borderBottom: '1 solid rgb(203, 213, 224)',
      paddingBottom: 2,
    },
    kvKey: { fontFamily: 'Helvetica-Bold', fontSize: 10 },
    kvValue: { fontSize: 10, marginBottom: 4 },
    watermark: {
      fontSize: 60,
      fontFamily: 'Helvetica-Bold',
      color: 'rgba(220, 38, 38, 0.12)',
      textAlign: 'center',
      marginTop: 200,
      transform: 'rotate(-30deg)',
    },
    footer: {
      position: 'absolute',
      bottom: 24,
      left: 48,
      right: 48,
      textAlign: 'center',
      fontSize: 8,
      color: 'rgb(113, 128, 150)',
      borderTop: '1 solid rgb(226, 232, 240)',
      paddingTop: 4,
    },
  });

  const componentSections = components.map((comp) => {
    const entries = flattenContent(comp.contentJsonb);
    return (
      <View key={comp.componentType}>
        <Text style={styles.sectionHeading}>{COMPONENT_LABELS[comp.componentType]}</Text>
        {entries.length === 0 ? (
          <Text style={styles.kvValue}>(no content)</Text>
        ) : (
          entries.map((e) => (
            <View key={e.key} style={{ marginBottom: 2 }}>
              <Text style={styles.kvKey}>{e.key}</Text>
              <Text style={styles.kvValue}>{e.value}</Text>
            </View>
          ))
        )}
      </View>
    );
  });

  const doc = (
    <Document
      title={`PCCP — ${version.deviceName} v${version.version}`}
      author={version.manufacturer}
      subject="Predetermined Change Control Plan"
      creator="Regula — Medical Device RA Assistant"
    >
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{version.deviceName}</Text>
        <Text style={styles.subtitle}>
          PCCP v{version.version} · {version.manufacturer} · Status: {version.status}
          {version.indication ? ` · Indication: ${version.indication}` : ''}
        </Text>
        {componentSections}
        {options.includeDraftWatermark ? <Text style={styles.watermark}>DRAFT</Text> : null}
        <Text style={styles.footer} fixed>
          Generated by Regula · Confidential — {version.deviceName} v{version.version}
        </Text>
      </Page>
    </Document>
  );

  const instance = pdf(doc);
  const blob = await instance.toBlob();
  const arrayBuffer = await blob.arrayBuffer();
  return Buffer.from(new Uint8Array(arrayBuffer));
}

export function getPdfFilename(version: PccpVersion): string {
  const safe = version.deviceName.replace(/[^a-zA-Z0-9-_]/g, '_');
  return `PCCP_${safe}_v${version.version}.pdf`;
}
