#!/usr/bin/env node
// @MX:NOTE Dev bootstrap — generates .env.local for fresh checkouts.
// REQ-QUAL-026: deterministic local setup; idempotent (skips if file exists).
// Run via: pnpm dev:bootstrap (registered in package.json).
//
// The script reads .env.example and substitutes placeholder secrets with
// `dev-placeholder-{key}` markers. lib/env.ts refuses these in production,
// so they cannot leak into a deployed environment.

import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname ?? __dirname, '..');
const EXAMPLE_PATH = path.join(ROOT, '.env.example');
const TARGET_PATH = path.join(ROOT, '.env.local');

// Map of env keys to dev-placeholder values. Anything not listed here keeps
// the value found in .env.example (e.g. NEXTAUTH_URL, POSTHOG_HOST).
const PLACEHOLDERS: Record<string, string> = {
  // Database — local Postgres default
  DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/regula_dev',

  // Auth.js v5
  AUTH_SECRET: 'dev-placeholder-auth-secret-padded-to-32-chars-min',
  AUTH_MICROSOFT_ENTRA_ID: 'dev-placeholder-microsoft',
  AUTH_MICROSOFT_ID: 'dev-placeholder-microsoft',
  AUTH_MICROSOFT_SECRET: 'dev-placeholder-microsoft-secret',
  AUTH_MICROSOFT_TENANT_ID: 'dev-placeholder-microsoft-tenant',
  AUTH_GOOGLE_ID: 'dev-placeholder-google',
  AUTH_GOOGLE_SECRET: 'dev-placeholder-google-secret',

  // LLM providers
  ANTHROPIC_API_KEY: 'dev-placeholder-anthropic',
  OPENAI_API_KEY: 'dev-placeholder-openai',
  COHERE_API_KEY: 'dev-placeholder-cohere',

  // Observability
  NEXT_PUBLIC_SENTRY_DSN: 'dev-placeholder-sentry',
  SENTRY_DSN: 'dev-placeholder-sentry',
  NEXT_PUBLIC_POSTHOG_KEY: 'dev-placeholder-posthog',
  LANGFUSE_PUBLIC_KEY: 'dev-placeholder-langfuse',
  LANGFUSE_SECRET_KEY: 'dev-placeholder-langfuse-secret',
};

export function transformLine(line: string): string {
  // Preserve comments and blank lines verbatim.
  if (line.trim().startsWith('#') || line.trim() === '') return line;

  // Match `KEY=value` (commented-out `# KEY=` is handled above).
  const match = line.match(/^([A-Z0-9_]+)\s*=(.*)$/);
  if (!match) return line;

  const key = match[1];
  if (key && key in PLACEHOLDERS) {
    return `${key}=${PLACEHOLDERS[key]}`;
  }
  return line;
}

export function generateEnvLocal(exampleContents: string): string {
  const header = [
    '# Generated by scripts/dev-bootstrap.ts — DO NOT COMMIT.',
    '# Replace dev-placeholder-* values before running anything that calls real APIs.',
    '# Delete this file and re-run `pnpm dev:bootstrap` to regenerate.',
    '',
  ].join('\n');

  const body = exampleContents.split(/\r?\n/).map(transformLine).join('\n');
  return `${header}${body}`;
}

function main(): void {
  if (fs.existsSync(TARGET_PATH)) {
    console.warn('⚠️  .env.local already exists, skipping. Delete it to regenerate.');
    process.exit(0);
  }

  if (!fs.existsSync(EXAMPLE_PATH)) {
    console.error('❌ .env.example not found at project root.');
    process.exit(1);
  }

  const example = fs.readFileSync(EXAMPLE_PATH, 'utf8');
  const generated = generateEnvLocal(example);
  fs.writeFileSync(TARGET_PATH, generated, 'utf8');

  console.log('✅ .env.local created with dev-placeholder values.');
  console.log('   Replace placeholders before invoking real LLM/SSO providers.');
}

// Only execute when run directly (not when imported by tests).
const invokedDirectly =
  typeof process !== 'undefined' &&
  process.argv[1] &&
  path.resolve(process.argv[1]) === path.resolve(import.meta.filename ?? __filename);

if (invokedDirectly) {
  main();
}
