// @MX:NOTE [AUTO] generateConsentDraft — REQ-CLININV-006 informed consent draft.
// @MX:SPEC SPEC-REGULA-CLINICAL-INVESTIGATION-001 (Issue #69, REQ-CLININV-006)

// @MX:LEGACY archived from lib
// @MX:REASON Produces a human-readable informed-consent DRAFT grounded in the
//           Helsinki principles and the applicable regulatory framework. No LLM
//           call in tier1 — the RA team edits the placeholder text directly.
//           Combined with a risk/benefit rationale per REQ-006.

import type { RegulatoryCitation } from './types';

const CITATIONS: RegulatoryCitation[] = [
  { source: '21 CFR', id: '50' },
  { source: 'EU MDR', id: 'Article 72' },
  { source: 'ISO', id: '14155' },
  { source: 'Declaration of Helsinki', id: 'informed consent principle' },
];

export interface ConsentDraftResult {
  consentText: string;
  riskBenefitRationale: string;
  citations: RegulatoryCitation[];
}

/**
 * REQ-CLININV-006 — generate an informed-consent DRAFT and risk/benefit rationale.
 *
 * The consent text follows the conventional section structure required by
 * 21 CFR 50.25 and ISO 14155 / Helsinki. Placeholders ([...]) mark sections the
 * RA-lead must finalize with device-specific language.
 */
export function generateConsentDraft(deviceContext: {
  deviceName?: string;
  intendedUse?: string;
  riskLevel?: string;
}): ConsentDraftResult {
  const device = deviceContext.deviceName ?? '[Device Name]';
  const use = deviceContext.intendedUse ?? '[Intended Use / Indications]';
  const risk = deviceContext.riskLevel ?? '[Risk Level]';

  const consentText = [
    `# Informed Consent Form (ICF) — Draft — ${device}`,
    '',
    '## 1. Purpose of the Study',
    `This clinical study evaluates the safety and performance of ${device} for the following intended use: ${use}.`,
    '',
    '## 2. Procedures',
    '[Describe study visits, duration, assessments, and any experimental procedures.]',
    '',
    '## 3. Risks and Discomforts',
    `[Documented risk level: ${risk}. Enumerate foreseeable risks, discomforts, and the probability/severity of each.]`,
    '',
    '## 4. Potential Benefits',
    '[Describe potential direct benefits to the subject and/or generalizable knowledge.]',
    '',
    '## 5. Alternatives',
    '[List available alternative procedures or treatments, including non-participation.]',
    '',
    '## 6. Confidentiality',
    '[Describe data handling, anonymization, and applicable privacy regulations (GDPR/HIPAA).]',
    '',
    '## 7. Compensation and Treatment for Injury',
    '[Per applicable regulation — describe medical treatment and compensation for study-related injury.]',
    '',
    '## 8. Voluntary Participation and Withdrawal',
    'Participation is voluntary. You may withdraw at any time without penalty or loss of rights.',
    '',
    '## 9. Contact Information',
    '[Principal investigator contact, 24-hour emergency line, IRB/EC contact.]',
    '',
    '_This ICF is a draft generated by Regula and must be reviewed and finalized by the RA-lead and approved by the IRB/EC before use._',
  ].join('\n');

  const riskBenefitRationale = [
    '## Risk/Benefit Rationale (REQ-006)',
    '',
    `The sponsor has determined the risk-benefit profile of ${device} supports proceeding with the investigation:`,
    '',
    `- Documented risk level: ${risk}.`,
    '- Foreseeable risks have been minimized through design controls and pre-clinical verification (ISO 14971).',
    '- Expected benefits: [clinical performance data supporting conformity assessment / market authorization].',
    '- Risk-benefit ratio is favorable compared to existing alternatives and to the standard of care.',
    '',
    'This rationale must be revisited at each protocol amendment and at study close-out.',
  ].join('\n');

  return { consentText, riskBenefitRationale, citations: CITATIONS };
}
