// @MX:NOTE [AUTO] buildIrbPackageDraft — REQ-CLININV-004 IRB/EC submission package draft.
// @MX:SPEC SPEC-REGULA-CLINICAL-INVESTIGATION-001 (Issue #69, REQ-CLININV-004/007, AC-03)

// @MX:LEGACY archived from lib
// @MX:REASON Generates the textual draft sections that constitute an IRB/EC
//           submission package. The output is a DRAFT only — actual eSubmit bundle
//           assembly (XML packaging, sponsor signature block, FDA Form 3514, EUDAMED
//           single-submission payload) is deferred to Issue 65 (eSubmit dependency).
//           See @MX:TODO below.
//
// Generates:
//   - IRB package cover letter + table of contents (21 CFR 56 / EU MDR Article 62(4))
//   - Optional consent draft (REQ-006, delegated to consent-generator)
//   - Optional investigator brochure (REQ-007, template scaffold)
//   - Optional monitoring plan (REQ-007, template scaffold)

import { authoritativeCitations } from './citation-enforcement';
import { generateConsentDraft } from './consent-generator';
import type { IrbPackageDraft, IrbPackageInput, RegulatoryCitation } from './types';

const CITATIONS: RegulatoryCitation[] = [
  { source: '21 CFR', id: '56' },
  { source: '21 CFR', id: '812.20(a)' },
  { source: '21 CFR', id: '812.25' },
  { source: 'EU MDR', id: 'Article 62(4)' },
  { source: 'ISO', id: '14155' },
];

/**
 * REQ-CLININV-004 — build IRB/EC submission package draft sections.
 *
 * @MX:TODO [AUTO] eSubmit bundle assembly (XML packaging + Form 3514 + EUDAMED
 *   single-submission payload) is DEFERRED to Issue 65 (eSubmit dependency).
 *   This function produces human-editable DRAFT text only; it does NOT produce
 *   a regulator-ready submission artifact.
 */
export function buildIrbPackageDraft(
  input: IrbPackageInput,
  deviceContext: { deviceName?: string; intendedUse?: string; riskLevel?: string },
  _retrievedSources: ReadonlyArray<{ citation: string; title?: string }> = [],
): IrbPackageDraft {
  const heading =
    input.pathway === 'fda_ide' ? 'IRB Submission Package' : 'Ethics Committee Submission Package';
  const device = deviceContext.deviceName ?? '[Device Name]';
  const use = deviceContext.intendedUse ?? '[Intended Use / Indications]';
  const risk = deviceContext.riskLevel ?? '[Risk Level]';

  const irbPackage = [
    `# ${heading} — Draft`,
    '',
    `Device: ${device}`,
    `Intended Use: ${use}`,
    `Risk Level: ${risk}`,
    '',
    '## 1. Cover Letter',
    '',
    'To the Institutional Review Board / Ethics Committee:',
    '',
    `We hereby submit the enclosed documentation for review of the clinical investigation of ${device}. ` +
      `This package is prepared in accordance with ${input.pathway === 'fda_ide' ? '21 CFR 56 (IRB) and 21 CFR 812 (IDE)' : 'EU MDR Article 62(4) and Annex XV'}.`,
    '',
    '## 2. Table of Contents',
    '',
    '  - Cover Letter',
    '  - Clinical Investigation Plan (CIP / Protocol)',
    '  - Investigator Brochure (IB)',
    '  - Informed Consent Form (ICF) Draft',
    '  - Risk Analysis Report (ISO 14971)',
    '  - Monitoring Plan',
    '  - Device IFU and Labeling Draft',
    '',
    '## 3. Compliance Attestation',
    '',
    'The sponsor attests that the investigation will be conducted in accordance with:',
    input.pathway === 'fda_ide'
      ? '  - 21 CFR 50 (Informed Consent)'
      : '  - EU MDR Article 72 (Subject Protection)' +
        '\n  - ISO 14155 (GCP for Clinical Investigations)' +
        '\n  - Declaration of Helsinki',
    '',
    '_This is a draft generated by Regula and requires RA-lead review and signature before submission._',
  ].join('\n');

  const result: IrbPackageDraft = {
    irbPackage,
    citations: [],
    confidence: 'authoritative',
  };

  if (input.includeConsentDraft) {
    result.consentDraft = generateConsentDraft(deviceContext).consentText;
  }
  if (input.includeBrochure) {
    result.brochure = buildInvestigatorBrochure(device);
  }
  if (input.includeMonitoringPlan) {
    result.monitoringPlan = buildMonitoringPlan(input.pathway);
  }

  // H-1 fix: CITATIONS are AUTHORITATIVE 21 CFR 56 / 812 / EU MDR Art 62(4)
  // statute references baked into the package template — NOT LLM-generated.
  // Grounded-by-construction → confidence='authoritative'. Do NOT route
  // through enforceCitations([]) (that would mark them 'unverified').
  // H-1 fix: CITATIONS are AUTHORITATIVE 21 CFR 56 / 812 / EU MDR Art 62(4)
  // statute references baked into the package template — NOT LLM-generated.
  // Grounded-by-construction → confidence='authoritative'. Do NOT route
  // through enforceCitations([]) (that would mark them 'unverified').
  const enforced = authoritativeCitations(CITATIONS);
  result.citations = enforced.citations;
  result.confidence = enforced.confidence;

  return result;
}

// REQ-CLININV-007 — investigator brochure template scaffold.
function buildInvestigatorBrochure(deviceName: string): string {
  return [
    `# Investigator Brochure (IB) — Draft — ${deviceName}`,
    '',
    '## 1. Device Description',
    '[Physical, chemical, biological, and functional characteristics]',
    '',
    '## 2. Intended Use / Indications',
    '[Clinical indications and target population]',
    '',
    '## 3. Risk Analysis Summary',
    '[Cross-reference to ISO 14971 risk-management report]',
    '',
    '## 4. Pre-clinical Study Summary',
    '[Bench testing, biocompatibility, animal study results]',
    '',
    '## 5. Prior Clinical Experience',
    '[Literature review and prior CER findings]',
    '',
    '## 6. Manufacturing and Quality',
    '[Sterilization, packaging, shelf-life, traceability]',
    '',
    '_Draft — RA-lead must finalize before submission._',
  ].join('\n');
}

// REQ-CLININV-007 — monitoring plan template scaffold.
function buildMonitoringPlan(pathway: 'fda_ide' | 'eu_mdr'): string {
  const anchor =
    pathway === 'fda_ide'
      ? '21 CFR 812.25(d), 812.40, 812.46'
      : 'EU MDR Article 72(3), ISO 14155 §8';
  return [
    '# Clinical Monitoring Plan — Draft',
    '',
    `Regulatory basis: ${anchor}`,
    '',
    '## 1. Monitoring Strategy',
    '[On-site + remote monitoring frequency, site selection criteria]',
    '',
    '## 2. Source Data Verification',
    '[CRF vs source document review plan, sampling rate]',
    '',
    '## 3. Adverse Event Reporting',
    '[Timelines for expedited vs routine AE reporting to sponsor / IRB / authority]',
    '',
    '## 4. Deviation Management',
    '[Protocol deviation classification and escalation]',
    '',
    '_Draft — RA-lead must finalize before submission._',
  ].join('\n');
}
